- name: razorpay
  url: ''
- name: zepto
  url: ''
- name: sharechat
  url: ''
- name: dream11
  url: ''
- name: swiggy
  url: ''
- name: zomato
  url: ''
- name: udaan
  url: ''
- name: jupiter
  url: ''
- name: khatabook
  url: ''
- name: zetwerk
  url: ''
- name: urbancompany
  url: ''
- name: unacademy
  url: ''
- name: upgrad
  url: ''
- name: rapido
  url: ''
- name: delhivery
  url: ''
- name: lenskart
  url: ''
- name: myntra
  url: ''
- name: nykaa
  url: ''
- name: mpl
  url: ''
- name: gameskraft
  url: ''
- name: zerodha
  url: ''
- name: smallcase
  url: ''
- name: mobikwik
  url: ''
- name: cleartax
  url: ''
- name: juspay
  url: ''
- name: chargebee
  url: ''
- name: freshworks
  url: ''
- name: zoho
  url: ''
- name: browserstack
  url: ''
- name: hasura
  url: ''
- name: postmanlabs
  url: ''
- name: innovaccer
  url: ''
- name: whatfix
  url: ''
- name: yellowai
  url: ''
- name: gupshup
  url: ''
- name: icertis
  url: ''
- name: sprinklr
  url: ''
- name: darwinbox
  url: ''
- name: leadsquared
  url: ''
- name: moengage
  url: ''
- name: clevertap
  url: ''
- name: netcoresmartech
  url: ''
- name: uniphore
  url: ''
- name: fractal
  url: ''
- name: tigeranalytics
  url: ''
- name: quantiphi
  url: ''
- name: cohesity
  url: ''
- name: nutanix
  url: ''
- name: atlassian
  url: ''
- name: uber
  url: ''
- name: hashicorp
  url: ''
- name: rippling
  url: ''
- name: retool
  url: ''
- name: redislabs
  url: ''
- name: snowflakecomputing
  url: ''
- name: salesforce
  url: ''
- name: intuit
  url: ''
- name: walmartglobaltech
  url: ''
- name: target
  url: ''
- name: lowes
  url: ''
- name: tesco
  url: ''
- name: optum
  url: ''
- name: oracle
  url: ''
- name: sap
  url: ''
- name: vmware
  url: ''
- name: arista
  url: ''
- name: juniper
  url: ''
- name: palo alto networks
  url: ''
- name: crowdstrike
  url: ''
- name: sentinelone
  url: ''
- name: snyk
  url: ''
- name: gong
  url: ''
- name: segment
  url: ''
- name: harness
  url: ''
- name: lacework
  url: ''
- name: dbtlabs
  url: ''
- name: timescale
  url: ''
